on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: copy
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{secrets.VPS}}
        key: ${{secrets.VPS_KEY}}
        source: "*"
        target: "~/binance"

    - name: run
      uses: fifsky/ssh-action@v0.0.6
      with:
        host: ${{secrets.VPS}}
        key: ${{secrets.VPS_KEY}}
        command: systemctl restart binance
