on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: copy
      uses: Burnett01/rsync-deployments@5.2.1
      with:
        switches: av
        remote_user: root
        remote_host: ${{secrets.VPS}}
        remote_key: ${{secrets.VPS_KEY}}
        path: "*"
        remote_path: "~/binance"

    - name: run
      uses: fifsky/ssh-action@v0.0.6
      with:
        host: ${{secrets.VPS}}
        key: ${{secrets.VPS_KEY}}
        command: systemctl restart binance
