on:
  push:
    branches: [ "master" ]
    
env:
  PROJECT_PATH: "~/QuantitativeTrading"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

#    - name: copy
#      uses: appleboy/scp-action@v0.0.1
#      with:
#        host: ${{secrets.VPS}}
#        username: root
#        key: ${{secrets.VPS_KEY}}
#        source: "*"
#        target: "~/binance"

    - name: run
      uses: fifsky/ssh-action@master
      with:
        host: ${{secrets.VPS}}
        key: ${{secrets.VPS_KEY}}
        command: systemctl restart binance
